package com.desk.java;


import java.awt.GridLayout;
import javax.swing.*;

public class Variables {
    Icon connected = new ImageIcon("001-switch.png");
    Icon disconnected = new ImageIcon("002-switch-1.png");
	Icon blank = new ImageIcon("rsz_blank.png");
        Icon vcc = new ImageIcon("rsz_positive.png");
        Icon ground = new ImageIcon("rsz_negative.png");
	//combo box array
	String[] partSelect = {"---","Light Sensor","PNP Transistor","NPN Transistor","Wire","Potentiometer","LED","Button"};
        String[] positive = {"Positive Voltage"};
        String[] negitive = {"Negative/Ground"};
	JPanel selectorPanel = new JPanel(new GridLayout(4,4,50,170));
        JTabbedPane tabbedPane = new JTabbedPane();
    public JComboBox partSelector1 = new JComboBox(positive);
    public JComboBox partSelector2 = new JComboBox(partSelect);
    public JComboBox partSelector3 = new JComboBox(partSelect);
    public JComboBox partSelector4 = new JComboBox(negitive);
    public JComboBox partSelector5 = new JComboBox(partSelect);
    public JComboBox partSelector6 = new JComboBox(partSelect);
    public JComboBox partSelector7 = new JComboBox(partSelect);
    public JComboBox partSelector8 = new JComboBox(partSelect);
    public JComboBox partSelector9 = new JComboBox(partSelect);
    public JComboBox partSelector10 = new JComboBox(partSelect);
    public JComboBox partSelector11 = new JComboBox(partSelect);
    public JComboBox partSelector12 = new JComboBox(partSelect);
    public JComboBox partSelector13 = new JComboBox(partSelect);
    public JComboBox partSelector14 = new JComboBox(partSelect);
    public JComboBox partSelector15 = new JComboBox(partSelect);
    public JComboBox partSelector16 = new JComboBox(partSelect);
	//outside panel
	JPanel outsidePanel = new JPanel();
        JPanel circuitPanel = new JPanel();
        JPanel runButtonsPanel = new JPanel();
        JPanel tutorialPanel = new JPanel();
	//pane label
	public JLabel paneLabel11 = new JLabel(vcc);
	public JLabel paneLabel12 = new JLabel(blank);
	public JLabel paneLabel13 = new JLabel(blank);
	public JLabel paneLabel14 = new JLabel(ground);
        public JLabel paneLabel21 = new JLabel(blank);
	public JLabel paneLabel22 = new JLabel(blank);
	public JLabel paneLabel23 = new JLabel(blank);
	public JLabel paneLabel24 = new JLabel(blank);
        public JLabel paneLabel31 = new JLabel(blank);
	public JLabel paneLabel32 = new JLabel(blank);
	public JLabel paneLabel33 = new JLabel(blank);
	public JLabel paneLabel34 = new JLabel(blank);
        public JLabel paneLabel41 = new JLabel(blank);
	public JLabel paneLabel42 = new JLabel(blank);
	public JLabel paneLabel43 = new JLabel(blank);
	public JLabel paneLabel44 = new JLabel(blank);
	JButton button11 = new JButton(disconnected);
	JButton button12 = new JButton(disconnected);
	JButton button13 = new JButton(disconnected);
        JButton button21 = new JButton(disconnected);
        JButton button22 = new JButton(disconnected);
        JButton button23 = new JButton(disconnected);
        JButton button24 = new JButton(disconnected);
	JButton button31 = new JButton(disconnected);
	JButton button32 = new JButton(disconnected);
	JButton button33 = new JButton(disconnected);
        JButton button41 = new JButton(disconnected);
        JButton button42 = new JButton(disconnected);
        JButton button43 = new JButton(disconnected);
        JButton button44 = new JButton(disconnected);
	JButton button51 = new JButton(disconnected);
	JButton button52 = new JButton(disconnected);
	JButton button53 = new JButton(disconnected);
        JButton button61 = new JButton(disconnected);
        JButton button62 = new JButton(disconnected);
        JButton button63 = new JButton(disconnected);
        JButton button64 = new JButton(disconnected);
        JButton button71 = new JButton(disconnected);
        JButton button72 = new JButton(disconnected);
        JButton button73 = new JButton(disconnected);
        
        JButton run = new JButton("Run");
        JButton stop =new JButton("Stop");
        JButton check = new JButton("Check");
        JButton clear = new JButton("Clear");
        
	Icon ldr = new ImageIcon("rsz_ldr.png");
	Icon led = new ImageIcon("rsz_led-diode-xxl.png");
	Icon pot = new ImageIcon("rsz_industry-potentiometer-icon.png");
	Icon PNPtransistor = new ImageIcon("rsz_transistor.png");
	Icon NPNtransistor = new ImageIcon("rsz_transistor.png");
	Icon button = new ImageIcon("rsz_button.png");
	Icon wire = new ImageIcon("line-128x128.png");
	Icon iconType1;
	Icon iconType2;
	Icon iconType3;
	Icon iconType4;
        Icon iconType5;
        Icon iconType6;
        Icon iconType7;
        Icon iconType8;
        Icon iconType9;
        Icon iconType10;
        Icon iconType11;
        Icon iconType12;
        Icon iconType13;
        Icon iconType14;
        Icon iconType15;
        Icon iconType16;
        boolean connect1 = false;
        boolean connect2 = false;
        boolean connect3 = false;
        boolean connect4 = false;
        boolean connect5 = false;
        boolean connect6 = false;
        boolean connect7 = false;
        boolean connect8 = false;
        boolean connect9 = false;
        boolean connect10 = false;
        boolean connect11 = false;
        boolean connect12 = false;
        boolean connect13 = false;
        boolean connect14 = false;
        boolean connect15 = false;
        boolean connect16 = false;
        boolean connect17 = false;
        boolean connect18 = false;
        boolean connect19 = false;
        boolean connect20 = false;
        boolean connect21 = false;
        boolean connect22 = false;
        boolean connect23 = false;
        boolean connect24 = false;
	String partName1 = "Positive Voltage";
	String partName2;
	String partName3;
	String partName4 = "Ground";
        String partName5;
        String partName6;
	String partName7;
	String partName8;
	String partName9;
        String partName10;
        String partName11;
	String partName12;
	String partName13;
	String partName14;
        String partName15;
        String partName16;
        
        boolean connectedToGround = false;
        String partPath = "";
        
        public boolean runConnect;
        
        JTextArea tutorial = new JTextArea("Tutorial and Quickstart Guide coming soon. " + '\n' + "Please ask Garrett for assistance or check out sites.google.com/view/brokenrobotlabs, Thanks", 20,20);
        
        public Variables(MainFrame in, GUI min){
            //setup selectorPanel
            tutorial.setEditable(false);
            tutorial.setWrapStyleWord(true);
	    button11.setContentAreaFilled(false);
	    button12.setContentAreaFilled(false);
	    button13.setContentAreaFilled(false);
            button21.setContentAreaFilled(false);
            button22.setContentAreaFilled(false);
            button23.setContentAreaFilled(false);
            button24.setContentAreaFilled(false);
            button31.setContentAreaFilled(false);
            button32.setContentAreaFilled(false);
            button33.setContentAreaFilled(false);
            button41.setContentAreaFilled(false);
            button42.setContentAreaFilled(false);
            button43.setContentAreaFilled(false);
            button44.setContentAreaFilled(false);
            button51.setContentAreaFilled(false);
            button52.setContentAreaFilled(false);
            button53.setContentAreaFilled(false);
            button61.setContentAreaFilled(false);
            button62.setContentAreaFilled(false);
            button63.setContentAreaFilled(false);
            button64.setContentAreaFilled(false);
            button71.setContentAreaFilled(false);
            button72.setContentAreaFilled(false);
            button73.setContentAreaFilled(false);
            button11.setBorder(null);
	    button12.setBorder(null);
	    button13.setBorder(null);
            button21.setBorder(null);
            button22.setBorder(null);
            button23.setBorder(null);
            button24.setBorder(null);
            button31.setBorder(null);
            button32.setBorder(null);
            button33.setBorder(null);
            button41.setBorder(null);
            button42.setBorder(null);
            button43.setBorder(null);
            button44.setBorder(null);
            button51.setBorder(null);
            button52.setBorder(null);
            button53.setBorder(null);
            button61.setBorder(null);
            button62.setBorder(null);
            button63.setBorder(null);
            button64.setBorder(null);
            button71.setBorder(null);
            button72.setBorder(null);
            button73.setBorder(null);
	    
	    
            }
}